language: c
matrix:
  include:
    - compiler: gcc
      env: GCOV_OPT="--enable-gcov"
    - compiler: gcc
      env: GCOV_OPT="--disable-gcov"
    - compiler: clang
      env: GCOV_OPT="--disable-gcov" # gcov code coverage only works with gcc, so don't run it with clang.
#Adding Power_jobs
    - compiler: gcc
      env: GCOV_OPT="--enable-gcov"
      arch: ppc64le
    - compiler: gcc
      env: GCOV_OPT="--disable-gcov"
      arch: ppc64le  
    - compiler: clang
      env: GCOV_OPT="--disable-gcov"
      arch: ppc64le
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap0.8-dev
  - sudo pip install cpp-coveralls
script:
  - autoreconf --install && ./configure $GCOV_OPT && make && make check
after_success:
  - if [ $GCOV_OPT == "--enable-gcov" ]; then coveralls ; fi
